import { should } from '@paulmillr/jsbt/test.js';
import { test as aes } from './aes.test.ts';
import { test as arx } from './arx.test.ts';
import { test as basic } from './basic.test.ts';
import { test as cmac } from './cmac.test.ts';
import { test as crosstest } from './crosstest.test.ts';
import './ff1.test.ts';
import { test as polyval } from './polyval.test.ts';
import { test as siv } from './siv.test.ts';
import { test as utils } from './utils.test.ts';
import { test as webcrypto } from './webcrypto.test.ts';
// import './errors.test.ts';

aes();
arx();
basic();
cmac();
crosstest();
polyval();
siv();
utils();
webcrypto();
should.runWhen(import.meta.url);
