name: Publish release
on:
  release:
    types: [created]
jobs:
  test-js:
    name: 'jsbt v0.3.0' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@973650a225c0344aa5f993a6cd63835a262077e9
    with:
      build-path: test/build
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      id-token: write
