name: Publish release
on:
  release:
    types: [created]
jobs:
  release-js:
    name: 'jsbt v0.3.4' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/release.yml@ce84a25be22ad27f4aa49a100def27f4c1827299
    with:
      build-path: test/build
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
    permissions:
      contents: write
      id-token: write
      attestations: write
