name: Run scheduled tests
on:
  schedule:
    - cron: '0 6 * * 1,4' # 06:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Slow large input tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@231cc389fe2f825b6531285ad8c275584bf76588
    with:
      npm-task: test:slow
