name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'jsbt v0.3.4' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@ce84a25be22ad27f4aa49a100def27f4c1827299
