name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'JS v0.2.2' # v0.2.2 == commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@4d4e3743023353f0bde7e6dc3b682cc9c1723232
