name: Run tests
on:
  - push
  - pull_request
jobs:
  test-js:
    name: 'jsbt v0.3.0' # Should match commit below
    uses: paulmillr/jsbt/.github/workflows/test-js.yml@973650a225c0344aa5f993a6cd63835a262077e9
