name: Run scheduled tests
on:
  schedule:
    - cron: '0 6 * * 1,4' # 06:00 bi-weekly (mon, thu)
  workflow_dispatch:
jobs:
  slow:
    name: Slow large input tests
    uses: paulmillr/jsbt/.github/workflows/test-custom.yml@a00dbc815760211c6f6986344b2da91512597810
    with:
      npm-task: test:slow
